apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio-ingress
spec:
  entryPoints:
    - web # Required to redirect from HTTP denniskrasnov.com
    - websecure
  routes:
  # Can't have match with empty services, therefore must combine hosts
  - match: Host(`krasnov.dev`) || Host(`denniskrasnov.com`)
    kind: Rule
    services:
    - name: portfolio-web
      namespace: portfolio
      port: 80
    middlewares:
    - name: portfolio-redirect
  tls:
    certResolver: letsencrypt